---
- name: Configure Apache in FreeBSD
  template:
    src: vhosts.j2
    dest: /usr/local/etc/apache24/Includes/{ my_pc }}.conf
  notify: restart apache
    
- name: Create target directory
  file: path=/var/www/html/{{ my_pc }} state=directory mode=0755

- name: Copy index file => FreeBSD
  template:
    src: index.html.j2
    dest: /var/www/html/{{ my_pc }}/index.html