---
- name: Configure Apache in Debian
  template:
    src: vhosts.j2
    dest: /etc/apache2/sites-enabled/{{ my_pc }}.conf
  notify: restart apache

- name: Copy index file => Debian
  template:
    src: index.html.j2
    dest: /var/www/html/{{ my_pc }}/{{ my_pc }}.html