---
- name: Configure Apache in RedHat
  template:
    src: vhosts.j2
    dest: /etc/httpd/conf.d/{{ my_pc }}.conf
  notify: restart apache

- name: Copy index file => RedHat
  template:
    src: index.html.j2
    dest: /var/www/html/{{ my_pc }}/index.html

