--- 
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

#  - name: Install the correct web server for RHEL
#    import_tasks: redhat.yml
#    when: ansible_facts['os_family']|lower == 'redhat'

#  - name: Install the correct web server for Debian
#    import_tasks: debian.yml
#    when: ansible_facts['os_family']|lower == 'debian'

#  - name: Install the correct web server for FreeBSD
#    import_tasks: freebsd.yml
#    when: ansible_facts['os_family']|lower == 'freebsd'

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

  
# Configure Apache.
- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
